### ISSUE TITLE
retrying block production 

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/hbbft-posdao-contracts#101]
after x seconds, if a block can't get produced, the network should restart the block production.

**Comment by SurfingNerd** [comment]
need to clarify this issue.
retrying block production, often referred to "phoenix protocol" (??) should be most of all a diamond-node implementation.
We need to work out if the contracts are part of this change.

**Comment by cryptonit** [comment]
i agree to my understanding its a node only thing
no contract is involved as contracts are just executed when a block is generated
this "phoenix protocol" is to avoid most kinds of stuck in a unable to finish block by just restart from scratch after a timeout is reached. maybe some kind of round counter is needed so block contributions and most important block seal mesage fit to the actual atempt

**Comment by SurfingNerd** [comment]
open ethereum issue: https://github.com/DMDcoin/openethereum-3.x/issues/52
