### ISSUE TITLE
No payout for validators that became unavailable during epoch.

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/hbbft-posdao-contracts#132]
Validators that got marked as unvavailable caused by the malicious report system (not implemented yet) but are part of the active validator set should not receive rewards.
This can be checked by comparing the stakingEpochStartTime  with validatorAvailableSince

**Comment by SurfingNerd** [comment]
actually the banning handling already handles the payout for validators. validator bans currently last 12 times the target epoch length, what would result in 6 days.

**Comment by cryptonit** [comment]
6 days could be to long deepends how easy a ban could be earned

48 hours which is 4 epochs could be better

but we need to make sure staking ui will show last 30 or 90 days how many times a validator candidate was hit by a ban so people can avoid staking on top

**Comment by SurfingNerd** [comment]
the banning system got removed: https://github.com/DMDcoin/diamond-contracts-core/issues/145
