### ISSUE TITLE
switch from a block based system to a time based system

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/hbbft-posdao-contracts#18]
AURA works fine seeing it as block based system.
All x seconds (typical 0 < x <= 60) a block is mined.
Therefore a Epoch length or Ban durations were defined as "Block numbers".

In HBBFT we need to think more about in Time, since in HBBFT there might be a block all X seconds, or there might be no block at all for a long time.

We need to switch to a time based system, instead of a block based system. 
Essential switching out getCurrentBlockNumber() with getCurrentTimestamp(), probably removing getCurrentBlockNumber() completly and making all tests time based.

**Comment by cryptonit** [comment]
dont remove get current blocknumber from api other projects or even we might need the function
and even we might need it for example for validator checking each other asking for actual blocknumber and the hash of that block and this way verify to be on same chain also a way to find and remove missbehaving validators

**Comment by SurfingNerd** [comment]
Done so far. #12 and #14 are follow up issues.
