### ISSUE TITLE
Investigate epoch by epoch claiming

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/hbbft-posdao-contracts#20]
The current implementation stores the epoch rewards in the BlockReward smart contracts.

Meaning it stores the pool data (stackers and stacking amount), 
and for every epoch and every pool a reward. 

see base/BlockRewardHbbftBase.sol:
```
  
    mapping(address => uint256[]) internal _epochsPoolGotRewardFor;

    /// @dev The maximum per-block reward distributed among the validators.
    uint256 public maxEpochReward;

    /// @dev The reward amount to be distributed in native coins among participants (the validator and their
    /// delegators) of the specified pool (mining address) for the specified staking epoch.
    mapping(uint256 => mapping(address => uint256)) public epochPoolNativeReward;

    /// @dev The total reward amount in native coins which is not yet distributed among pools.
    uint256 public nativeRewardUndistributed;

    /// @dev The total amount staked into the specified pool (mining address)
    /// before the specified staking epoch. Filled by the `_snapshotPoolStakeAmounts` function.
    mapping(uint256 => mapping(address => uint256)) public snapshotPoolTotalStakeAmount;

    /// @dev The validator's amount staked into the specified pool (mining address)
    /// before the specified staking epoch. Filled by the `_snapshotPoolStakeAmounts` function.
    mapping(uint256 => mapping(address => uint256)) public snapshotPoolValidatorStakeAmount;

    /// @dev The validator's min reward percent which was actual at the specified staking epoch.
    /// This percent is taken from the VALIDATOR_MIN_REWARD_PERCENT constant and saved for every staking epoch
    /// by the `reward` function. Used by the `delegatorShare` and `validatorShare` public getters.
    /// This is needed to have an ability to change validator's min reward percent in the VALIDATOR_MIN_REWARD_PERCENT
    /// constant by upgrading the contract.
    mapping(uint256 => uint256) public validatorMinRewardPercent;
```
The data is stored for every epoch, and every epoch get's claimed separately.
This involves a lot of loops and complexity in the claiming logic.
The benefit of doing so is not clear, and needs to get further investigated.
(what is the PRO side for this approach ?)

one Pro is:
- It is tested
- it is audited
- it is used in the real world on xDai, we don't know problems with it.

On the Contra we have:

The storage and computational overhead of all this, comes with a heavy cost, 
even limiting possibilities, like having shorter Epochs.

**Comment by cryptonit** [comment]
we can expect never more then ~2000 people are involved in  running a validator and dPOS staker on top

how network would handle 2000 transactions once every 12 hours
we for sure dont want 2000 single transactions
ethereum is similar to bitcoin able have multiple recipients in a single transaction?
so it could be like 10 transactions with 200 reciepients

fees are paid by system as they are executed in rewards smart contracts?

how much MB blockchain bloat 20 transactions with 200 recipients would create per day

**Comment by SurfingNerd** [comment]
DB bloat should be neglectable.
following up issue: Implementing automatic reward restaking:
https://github.com/DMDcoin/hbbft-posdao-contracts/issues/43
