### ISSUE TITLE
Handle failing validator set switch

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/hbbft-posdao-contracts#58]
It is possible that a pending validator gets elected, but fails to send it's Acks and Parts to the KeyGenHistory.
In this case, the failing validators get banned for some time, and  new backup validators need to get picked up.

**Comment by cryptonit** [comment]
as far as i remember last meeting we try dedect such missbehavior already at the phase that submit the smalller size file so we dont need to store the bigger size files for a elected set that will be replaced

**Comment by cryptonit** [comment]
additional i suggest we have a alive check of elected validators pre starting keygen. example just ask all elected nodes for the random number of last block. if not all answer correct we elect again a new set. repeat until we have a set where all did answer correct. this way chance one of this set will not be able provide act/part is strong reduced. nodes who dont answer with correct random number needs to be blocked for some time (like 5 days (10 epochs)

**Comment by SurfingNerd** [comment]
yes, that can be done this way by using malice reports prior the voting.

**Comment by SurfingNerd** [comment]
changed implementation strategy:

Time based bans have shown to be very problematic in this context.
A node that got unresponsive might just keep to be unresponsive in the future, causing trouble each epoch switch.

A new system was implemented, that addresses this problem:
Instead of Banning, a node get's tracked as available or unavailable on the blockchain.
A node becomes unavailable once it got elected and does not manage to write it's key shares.
A node becomes available again, by notifying the smart contract any time.
Currently, there is no further punishment involved.  
A node that misses out it's key generation, potentially looses one epoch.
In a scenario were multiple nodes miss out, this ensures that reactive node operators manage to get a second chance, and do not loose an epoch. A very  healthy incentive for the network. Incentives monitory, fall over systems and automation.

**Comment by SurfingNerd** [comment]
handle failing validator set switch is implemented in the pull request: 
https://github.com/DMDcoin/hbbft-posdao-contracts/pull/66
