### ISSUE TITLE
50k stacking limit

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/hbbft-posdao-contracts#80]
For coineconomic reasons a staking limit of 50K is planned.
That means following operations are not allowed:

- creating a validator with more than 50K stake
- delegating on a Node what would result in a Node that has 50K+ stake.
- moving a delegation stake to a new validator what would result into a 50k+ stake.

When developing something like [automatic epoch reward restaking](https://github.com/DMDcoin/hbbft-posdao-contracts/issues/43) this limit should be ignored.

- [x] new variable
- [x] initializer contract
- [x] initializer test
- [x] network creation scripts
- [x] contract upgrade handling
- [x] unit test failiure inclusion

**Comment by SurfingNerd** [comment]
todo: 
Define if it should be possible to change the value beyond current limits or not.

**Comment by cryptonit** [comment]
as the coin economic framework
max total coins
wont change
and the security of network need a healthy competition of validator candidates
this values wont change

as it allows creation of candidates between 10000 and 50000 size the spectrum is broad enough

no change of min create candidate stake of 10000 max total stake of 50000 and min delegated stake of 100 is needed
this values can be hardcoded
