### ISSUE TITLE
Automatic validator count sweet spot targeting

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/hbbft-posdao-contracts#84]
Situation:
If there are less validators than max validators,
the contracts currently selects "all" validators.

In Unlucky situations, ALL validators can be a sour spot.
Like 6 Validators is a sour spot. It allows as many failing validator than the last sweet spot (4), 
but has 2 additional validators that must not fail. 

The sweet spots are:
4 - 7 - 10 - 13 - 16 - 19 - 22 - 25

The sour spots are in between. example:
4: good, a sweet spot 25% can fail.
5: bad: only 20% can fail
6: worst: only 16,66% can fail
7: good, the next sweet spot: 28.57% can fail.

Proposed solution:
If "all" validators count is not a sweet spot, there will be election with the number of validators equal to the biggest possible sweet spot.
Proposed solution: Only apply this rule for n > 4.

**Comment by cryptonit** [comment]
19 is also a sweet spot

3x1+1=4
3x2+1=7
3x3+1=10
3x4+1=13
3x5+1=16
3x6+1=19
3x7+1=21
3x1+1=25

**Comment by SurfingNerd** [comment]
works fine, never got a problem with this feature.
Note: Sweet Spot targeting is still only active for validator sets > 4.
Open for discusssion,
both takes have their pro and contras.
However, this is a very unusual scenario anyway, we always should have validator set sizes > 4.
